services:
  
  redis:
    image: redis:8.8-m03-alpine3.23
    ports:
      - 6379:6379
    environment:
            - REDIS_ARGS=--requirepass yourpassword --appendonly yes
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
      environment:
        - ConnectionStrings__Postgres=Host=db;Port=5432;Database=example;Username=admin;Password=example
      build:
        context: .
        target: final
      ports:
        - 9670:8080
      depends_on:
        db:
          condition: service_healthy
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt

